namespace QuanLyThuVienSach.GUI.GUI_THUKHO
{
    partial class AddBook_WareHouse
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AddBook_WareHouse));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.txtSoLanTaiBan = new Bunifu.UI.WinForms.BunifuTextBox();
            this.panel1 = new System.Windows.Forms.Panel();
            this.txtTacGia = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.bt_Exit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.bt_OK = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.label6 = new System.Windows.Forms.Label();
            this.txtGiaBan = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label7 = new System.Windows.Forms.Label();
            this.txtGiaMua = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuPanel11 = new Bunifu.UI.WinForms.BunifuPanel();
            this.txtNameBook = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label8 = new System.Windows.Forms.Label();
            this.txtSoLuong = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.label9 = new System.Windows.Forms.Label();
            this.txtNamxuatban = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtTheLoai = new Bunifu.UI.WinForms.BunifuTextBox();
            this.SuspendLayout();
            // 
            // txtSoLanTaiBan
            // 
            this.txtSoLanTaiBan.AcceptsReturn = false;
            this.txtSoLanTaiBan.AcceptsTab = false;
            this.txtSoLanTaiBan.AnimationSpeed = 200;
            this.txtSoLanTaiBan.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSoLanTaiBan.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSoLanTaiBan.AutoSizeHeight = true;
            this.txtSoLanTaiBan.BackColor = System.Drawing.Color.Transparent;
            this.txtSoLanTaiBan.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSoLanTaiBan.BackgroundImage")));
            this.txtSoLanTaiBan.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.txtSoLanTaiBan.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtSoLanTaiBan.BorderColorDisabled = System.Drawing.Color.Silver;
            this.txtSoLanTaiBan.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSoLanTaiBan.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.txtSoLanTaiBan.BorderRadius = 15;
            this.txtSoLanTaiBan.BorderThickness = 1;
            this.txtSoLanTaiBan.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSoLanTaiBan.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSoLanTaiBan.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtSoLanTaiBan.DefaultText = "";
            this.txtSoLanTaiBan.FillColor = System.Drawing.Color.White;
            this.txtSoLanTaiBan.HideSelection = true;
            this.txtSoLanTaiBan.IconLeft = null;
            this.txtSoLanTaiBan.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSoLanTaiBan.IconPadding = 10;
            this.txtSoLanTaiBan.IconRight = null;
            this.txtSoLanTaiBan.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSoLanTaiBan.Lines = new string[0];
            this.txtSoLanTaiBan.Location = new System.Drawing.Point(819, 92);
            this.txtSoLanTaiBan.Margin = new System.Windows.Forms.Padding(4);
            this.txtSoLanTaiBan.MaxLength = 32767;
            this.txtSoLanTaiBan.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSoLanTaiBan.Modified = false;
            this.txtSoLanTaiBan.Multiline = false;
            this.txtSoLanTaiBan.Name = "txtSoLanTaiBan";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSoLanTaiBan.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.Silver;
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSoLanTaiBan.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSoLanTaiBan.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSoLanTaiBan.OnIdleState = stateProperties4;
            this.txtSoLanTaiBan.Padding = new System.Windows.Forms.Padding(4);
            this.txtSoLanTaiBan.PasswordChar = '\0';
            this.txtSoLanTaiBan.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSoLanTaiBan.PlaceholderText = "Enter text";
            this.txtSoLanTaiBan.ReadOnly = false;
            this.txtSoLanTaiBan.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSoLanTaiBan.SelectedText = "";
            this.txtSoLanTaiBan.SelectionLength = 0;
            this.txtSoLanTaiBan.SelectionStart = 0;
            this.txtSoLanTaiBan.ShortcutsEnabled = true;
            this.txtSoLanTaiBan.Size = new System.Drawing.Size(340, 48);
            this.txtSoLanTaiBan.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSoLanTaiBan.TabIndex = 98;
            this.txtSoLanTaiBan.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSoLanTaiBan.TextMarginBottom = 0;
            this.txtSoLanTaiBan.TextMarginLeft = 3;
            this.txtSoLanTaiBan.TextMarginTop = 1;
            this.txtSoLanTaiBan.TextPlaceholder = "Enter text";
            this.txtSoLanTaiBan.UseSystemPasswordChar = false;
            this.txtSoLanTaiBan.WordWrap = true;
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(1272, 59);
            this.panel1.TabIndex = 104;
            // 
            // txtTacGia
            // 
            this.txtTacGia.AcceptsReturn = false;
            this.txtTacGia.AcceptsTab = false;
            this.txtTacGia.AnimationSpeed = 200;
            this.txtTacGia.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTacGia.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTacGia.AutoSizeHeight = true;
            this.txtTacGia.BackColor = System.Drawing.Color.Transparent;
            this.txtTacGia.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTacGia.BackgroundImage")));
            this.txtTacGia.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.txtTacGia.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtTacGia.BorderColorDisabled = System.Drawing.Color.Silver;
            this.txtTacGia.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtTacGia.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.txtTacGia.BorderRadius = 15;
            this.txtTacGia.BorderThickness = 1;
            this.txtTacGia.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTacGia.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTacGia.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtTacGia.DefaultText = "";
            this.txtTacGia.FillColor = System.Drawing.Color.White;
            this.txtTacGia.HideSelection = true;
            this.txtTacGia.IconLeft = null;
            this.txtTacGia.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTacGia.IconPadding = 10;
            this.txtTacGia.IconRight = null;
            this.txtTacGia.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTacGia.Lines = new string[0];
            this.txtTacGia.Location = new System.Drawing.Point(261, 153);
            this.txtTacGia.Margin = new System.Windows.Forms.Padding(4);
            this.txtTacGia.MaxLength = 32767;
            this.txtTacGia.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTacGia.Modified = false;
            this.txtTacGia.Multiline = false;
            this.txtTacGia.Name = "txtTacGia";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTacGia.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Silver;
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTacGia.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTacGia.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTacGia.OnIdleState = stateProperties8;
            this.txtTacGia.Padding = new System.Windows.Forms.Padding(4);
            this.txtTacGia.PasswordChar = '\0';
            this.txtTacGia.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTacGia.PlaceholderText = "Enter text";
            this.txtTacGia.ReadOnly = false;
            this.txtTacGia.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTacGia.SelectedText = "";
            this.txtTacGia.SelectionLength = 0;
            this.txtTacGia.SelectionStart = 0;
            this.txtTacGia.ShortcutsEnabled = true;
            this.txtTacGia.Size = new System.Drawing.Size(340, 48);
            this.txtTacGia.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTacGia.TabIndex = 105;
            this.txtTacGia.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTacGia.TextMarginBottom = 0;
            this.txtTacGia.TextMarginLeft = 3;
            this.txtTacGia.TextMarginTop = 1;
            this.txtTacGia.TextPlaceholder = "Enter text";
            this.txtTacGia.UseSystemPasswordChar = false;
            this.txtTacGia.WordWrap = true;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.Color.White;
            this.label3.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.label3.Location = new System.Drawing.Point(126, 169);
            this.label3.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(59, 19);
            this.label3.TabIndex = 103;
            this.label3.Text = "Author";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.BackColor = System.Drawing.Color.White;
            this.label2.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.label2.Location = new System.Drawing.Point(126, 108);
            this.label2.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(91, 19);
            this.label2.TabIndex = 88;
            this.label2.Text = "Name Book";
            // 
            // bt_Exit
            // 
            this.bt_Exit.AllowAnimations = true;
            this.bt_Exit.AllowMouseEffects = true;
            this.bt_Exit.AllowToggling = false;
            this.bt_Exit.AnimationSpeed = 200;
            this.bt_Exit.AutoGenerateColors = false;
            this.bt_Exit.AutoRoundBorders = false;
            this.bt_Exit.AutoSizeLeftIcon = true;
            this.bt_Exit.AutoSizeRightIcon = true;
            this.bt_Exit.BackColor = System.Drawing.Color.Transparent;
            this.bt_Exit.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.bt_Exit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bt_Exit.BackgroundImage")));
            this.bt_Exit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_Exit.ButtonText = "Exit";
            this.bt_Exit.ButtonTextMarginLeft = 0;
            this.bt_Exit.ColorContrastOnClick = 45;
            this.bt_Exit.ColorContrastOnHover = 45;
            this.bt_Exit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bt_Exit.CustomizableEdges = borderEdges1;
            this.bt_Exit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bt_Exit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bt_Exit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bt_Exit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bt_Exit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bt_Exit.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bt_Exit.ForeColor = System.Drawing.Color.DarkGray;
            this.bt_Exit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bt_Exit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bt_Exit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bt_Exit.IconMarginLeft = 11;
            this.bt_Exit.IconPadding = 14;
            this.bt_Exit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bt_Exit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bt_Exit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bt_Exit.IconSize = 5;
            this.bt_Exit.IdleBorderColor = System.Drawing.Color.Black;
            this.bt_Exit.IdleBorderRadius = 20;
            this.bt_Exit.IdleBorderThickness = 2;
            this.bt_Exit.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.bt_Exit.IdleIconLeftImage = null;
            this.bt_Exit.IdleIconRightImage = null;
            this.bt_Exit.IndicateFocus = false;
            this.bt_Exit.Location = new System.Drawing.Point(651, 416);
            this.bt_Exit.Margin = new System.Windows.Forms.Padding(4);
            this.bt_Exit.Name = "bt_Exit";
            this.bt_Exit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bt_Exit.OnDisabledState.BorderRadius = 20;
            this.bt_Exit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_Exit.OnDisabledState.BorderThickness = 2;
            this.bt_Exit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bt_Exit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bt_Exit.OnDisabledState.IconLeftImage = null;
            this.bt_Exit.OnDisabledState.IconRightImage = null;
            this.bt_Exit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bt_Exit.onHoverState.BorderRadius = 20;
            this.bt_Exit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_Exit.onHoverState.BorderThickness = 2;
            this.bt_Exit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bt_Exit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bt_Exit.onHoverState.IconLeftImage = null;
            this.bt_Exit.onHoverState.IconRightImage = null;
            this.bt_Exit.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.bt_Exit.OnIdleState.BorderRadius = 20;
            this.bt_Exit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_Exit.OnIdleState.BorderThickness = 2;
            this.bt_Exit.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.bt_Exit.OnIdleState.ForeColor = System.Drawing.Color.DarkGray;
            this.bt_Exit.OnIdleState.IconLeftImage = null;
            this.bt_Exit.OnIdleState.IconRightImage = null;
            this.bt_Exit.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.bt_Exit.OnPressedState.BorderRadius = 20;
            this.bt_Exit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_Exit.OnPressedState.BorderThickness = 2;
            this.bt_Exit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.bt_Exit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bt_Exit.OnPressedState.IconLeftImage = null;
            this.bt_Exit.OnPressedState.IconRightImage = null;
            this.bt_Exit.Size = new System.Drawing.Size(229, 49);
            this.bt_Exit.TabIndex = 101;
            this.bt_Exit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bt_Exit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bt_Exit.TextMarginLeft = 0;
            this.bt_Exit.TextPadding = new System.Windows.Forms.Padding(0);
            this.bt_Exit.UseDefaultRadiusAndThickness = true;
            this.bt_Exit.Click += new System.EventHandler(this.bt_Exit_Click);
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.BackColor = System.Drawing.Color.White;
            this.label4.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.label4.Location = new System.Drawing.Point(126, 289);
            this.label4.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(116, 19);
            this.label4.TabIndex = 89;
            this.label4.Text = "Publishing year";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.BackColor = System.Drawing.Color.White;
            this.label5.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.label5.Location = new System.Drawing.Point(648, 169);
            this.label5.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(110, 19);
            this.label5.TabIndex = 90;
            this.label5.Text = "Purchase price";
            // 
            // bt_OK
            // 
            this.bt_OK.AllowAnimations = true;
            this.bt_OK.AllowMouseEffects = true;
            this.bt_OK.AllowToggling = false;
            this.bt_OK.AnimationSpeed = 200;
            this.bt_OK.AutoGenerateColors = false;
            this.bt_OK.AutoRoundBorders = false;
            this.bt_OK.AutoSizeLeftIcon = true;
            this.bt_OK.AutoSizeRightIcon = true;
            this.bt_OK.BackColor = System.Drawing.Color.Transparent;
            this.bt_OK.BackColor1 = System.Drawing.Color.White;
            this.bt_OK.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bt_OK.BackgroundImage")));
            this.bt_OK.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_OK.ButtonText = "OK";
            this.bt_OK.ButtonTextMarginLeft = 0;
            this.bt_OK.ColorContrastOnClick = 45;
            this.bt_OK.ColorContrastOnHover = 45;
            this.bt_OK.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bt_OK.CustomizableEdges = borderEdges2;
            this.bt_OK.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bt_OK.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bt_OK.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bt_OK.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bt_OK.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bt_OK.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bt_OK.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(43)))), ((int)(((byte)(60)))));
            this.bt_OK.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bt_OK.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bt_OK.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bt_OK.IconMarginLeft = 11;
            this.bt_OK.IconPadding = 14;
            this.bt_OK.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bt_OK.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bt_OK.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bt_OK.IconSize = 5;
            this.bt_OK.IdleBorderColor = System.Drawing.Color.DimGray;
            this.bt_OK.IdleBorderRadius = 20;
            this.bt_OK.IdleBorderThickness = 2;
            this.bt_OK.IdleFillColor = System.Drawing.Color.White;
            this.bt_OK.IdleIconLeftImage = null;
            this.bt_OK.IdleIconRightImage = null;
            this.bt_OK.IndicateFocus = false;
            this.bt_OK.Location = new System.Drawing.Point(372, 416);
            this.bt_OK.Margin = new System.Windows.Forms.Padding(4);
            this.bt_OK.Name = "bt_OK";
            this.bt_OK.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bt_OK.OnDisabledState.BorderRadius = 20;
            this.bt_OK.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_OK.OnDisabledState.BorderThickness = 2;
            this.bt_OK.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bt_OK.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bt_OK.OnDisabledState.IconLeftImage = null;
            this.bt_OK.OnDisabledState.IconRightImage = null;
            this.bt_OK.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bt_OK.onHoverState.BorderRadius = 20;
            this.bt_OK.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_OK.onHoverState.BorderThickness = 2;
            this.bt_OK.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bt_OK.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bt_OK.onHoverState.IconLeftImage = null;
            this.bt_OK.onHoverState.IconRightImage = null;
            this.bt_OK.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.bt_OK.OnIdleState.BorderRadius = 20;
            this.bt_OK.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_OK.OnIdleState.BorderThickness = 2;
            this.bt_OK.OnIdleState.FillColor = System.Drawing.Color.White;
            this.bt_OK.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(43)))), ((int)(((byte)(60)))));
            this.bt_OK.OnIdleState.IconLeftImage = null;
            this.bt_OK.OnIdleState.IconRightImage = null;
            this.bt_OK.OnPressedState.BorderColor = System.Drawing.Color.Silver;
            this.bt_OK.OnPressedState.BorderRadius = 20;
            this.bt_OK.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_OK.OnPressedState.BorderThickness = 2;
            this.bt_OK.OnPressedState.FillColor = System.Drawing.Color.White;
            this.bt_OK.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(43)))), ((int)(((byte)(60)))));
            this.bt_OK.OnPressedState.IconLeftImage = null;
            this.bt_OK.OnPressedState.IconRightImage = null;
            this.bt_OK.Size = new System.Drawing.Size(229, 49);
            this.bt_OK.TabIndex = 99;
            this.bt_OK.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bt_OK.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bt_OK.TextMarginLeft = 0;
            this.bt_OK.TextPadding = new System.Windows.Forms.Padding(0);
            this.bt_OK.UseDefaultRadiusAndThickness = true;
            this.bt_OK.Click += new System.EventHandler(this.bt_OK_Click);
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.BackColor = System.Drawing.Color.White;
            this.label6.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.label6.Location = new System.Drawing.Point(648, 231);
            this.label6.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(43, 19);
            this.label6.TabIndex = 91;
            this.label6.Text = "Price";
            // 
            // txtGiaBan
            // 
            this.txtGiaBan.AcceptsReturn = false;
            this.txtGiaBan.AcceptsTab = false;
            this.txtGiaBan.AnimationSpeed = 200;
            this.txtGiaBan.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtGiaBan.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtGiaBan.AutoSizeHeight = true;
            this.txtGiaBan.BackColor = System.Drawing.Color.Transparent;
            this.txtGiaBan.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtGiaBan.BackgroundImage")));
            this.txtGiaBan.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.txtGiaBan.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtGiaBan.BorderColorDisabled = System.Drawing.Color.Silver;
            this.txtGiaBan.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtGiaBan.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.txtGiaBan.BorderRadius = 15;
            this.txtGiaBan.BorderThickness = 1;
            this.txtGiaBan.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtGiaBan.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtGiaBan.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtGiaBan.DefaultText = "";
            this.txtGiaBan.FillColor = System.Drawing.Color.White;
            this.txtGiaBan.HideSelection = true;
            this.txtGiaBan.IconLeft = null;
            this.txtGiaBan.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtGiaBan.IconPadding = 10;
            this.txtGiaBan.IconRight = null;
            this.txtGiaBan.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtGiaBan.Lines = new string[0];
            this.txtGiaBan.Location = new System.Drawing.Point(819, 214);
            this.txtGiaBan.Margin = new System.Windows.Forms.Padding(4);
            this.txtGiaBan.MaxLength = 32767;
            this.txtGiaBan.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtGiaBan.Modified = false;
            this.txtGiaBan.Multiline = false;
            this.txtGiaBan.Name = "txtGiaBan";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtGiaBan.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Silver;
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtGiaBan.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtGiaBan.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtGiaBan.OnIdleState = stateProperties12;
            this.txtGiaBan.Padding = new System.Windows.Forms.Padding(4);
            this.txtGiaBan.PasswordChar = '\0';
            this.txtGiaBan.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtGiaBan.PlaceholderText = "Enter text";
            this.txtGiaBan.ReadOnly = false;
            this.txtGiaBan.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtGiaBan.SelectedText = "";
            this.txtGiaBan.SelectionLength = 0;
            this.txtGiaBan.SelectionStart = 0;
            this.txtGiaBan.ShortcutsEnabled = true;
            this.txtGiaBan.Size = new System.Drawing.Size(340, 48);
            this.txtGiaBan.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtGiaBan.TabIndex = 97;
            this.txtGiaBan.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtGiaBan.TextMarginBottom = 0;
            this.txtGiaBan.TextMarginLeft = 3;
            this.txtGiaBan.TextMarginTop = 1;
            this.txtGiaBan.TextPlaceholder = "Enter text";
            this.txtGiaBan.UseSystemPasswordChar = false;
            this.txtGiaBan.WordWrap = true;
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.BackColor = System.Drawing.Color.White;
            this.label7.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.label7.Location = new System.Drawing.Point(647, 106);
            this.label7.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(145, 19);
            this.label7.TabIndex = 92;
            this.label7.Text = "Number of reprints";
            // 
            // txtGiaMua
            // 
            this.txtGiaMua.AcceptsReturn = false;
            this.txtGiaMua.AcceptsTab = false;
            this.txtGiaMua.AnimationSpeed = 200;
            this.txtGiaMua.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtGiaMua.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtGiaMua.AutoSizeHeight = true;
            this.txtGiaMua.BackColor = System.Drawing.Color.Transparent;
            this.txtGiaMua.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtGiaMua.BackgroundImage")));
            this.txtGiaMua.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.txtGiaMua.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtGiaMua.BorderColorDisabled = System.Drawing.Color.Silver;
            this.txtGiaMua.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtGiaMua.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.txtGiaMua.BorderRadius = 15;
            this.txtGiaMua.BorderThickness = 1;
            this.txtGiaMua.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtGiaMua.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtGiaMua.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtGiaMua.DefaultText = "";
            this.txtGiaMua.FillColor = System.Drawing.Color.White;
            this.txtGiaMua.HideSelection = true;
            this.txtGiaMua.IconLeft = null;
            this.txtGiaMua.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtGiaMua.IconPadding = 10;
            this.txtGiaMua.IconRight = null;
            this.txtGiaMua.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtGiaMua.Lines = new string[0];
            this.txtGiaMua.Location = new System.Drawing.Point(819, 153);
            this.txtGiaMua.Margin = new System.Windows.Forms.Padding(4);
            this.txtGiaMua.MaxLength = 32767;
            this.txtGiaMua.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtGiaMua.Modified = false;
            this.txtGiaMua.Multiline = false;
            this.txtGiaMua.Name = "txtGiaMua";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtGiaMua.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Silver;
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtGiaMua.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtGiaMua.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtGiaMua.OnIdleState = stateProperties16;
            this.txtGiaMua.Padding = new System.Windows.Forms.Padding(4);
            this.txtGiaMua.PasswordChar = '\0';
            this.txtGiaMua.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtGiaMua.PlaceholderText = "Enter text";
            this.txtGiaMua.ReadOnly = false;
            this.txtGiaMua.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtGiaMua.SelectedText = "";
            this.txtGiaMua.SelectionLength = 0;
            this.txtGiaMua.SelectionStart = 0;
            this.txtGiaMua.ShortcutsEnabled = true;
            this.txtGiaMua.Size = new System.Drawing.Size(340, 48);
            this.txtGiaMua.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtGiaMua.TabIndex = 96;
            this.txtGiaMua.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtGiaMua.TextMarginBottom = 0;
            this.txtGiaMua.TextMarginLeft = 3;
            this.txtGiaMua.TextMarginTop = 1;
            this.txtGiaMua.TextPlaceholder = "Enter text";
            this.txtGiaMua.UseSystemPasswordChar = false;
            this.txtGiaMua.WordWrap = true;
            // 
            // bunifuPanel11
            // 
            this.bunifuPanel11.BackgroundColor = System.Drawing.Color.Gray;
            this.bunifuPanel11.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel11.BackgroundImage")));
            this.bunifuPanel11.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel11.BorderColor = System.Drawing.Color.Gray;
            this.bunifuPanel11.BorderRadius = 5;
            this.bunifuPanel11.BorderThickness = 0;
            this.bunifuPanel11.Enabled = false;
            this.bunifuPanel11.Location = new System.Drawing.Point(76, 92);
            this.bunifuPanel11.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuPanel11.Name = "bunifuPanel11";
            this.bunifuPanel11.ShowBorders = true;
            this.bunifuPanel11.Size = new System.Drawing.Size(3, 308);
            this.bunifuPanel11.TabIndex = 93;
            // 
            // txtNameBook
            // 
            this.txtNameBook.AcceptsReturn = false;
            this.txtNameBook.AcceptsTab = false;
            this.txtNameBook.AnimationSpeed = 200;
            this.txtNameBook.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNameBook.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNameBook.AutoSizeHeight = true;
            this.txtNameBook.BackColor = System.Drawing.Color.Transparent;
            this.txtNameBook.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNameBook.BackgroundImage")));
            this.txtNameBook.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.txtNameBook.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNameBook.BorderColorDisabled = System.Drawing.Color.Silver;
            this.txtNameBook.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNameBook.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.txtNameBook.BorderRadius = 15;
            this.txtNameBook.BorderThickness = 1;
            this.txtNameBook.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNameBook.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNameBook.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtNameBook.DefaultText = "";
            this.txtNameBook.FillColor = System.Drawing.Color.White;
            this.txtNameBook.HideSelection = true;
            this.txtNameBook.IconLeft = null;
            this.txtNameBook.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNameBook.IconPadding = 10;
            this.txtNameBook.IconRight = null;
            this.txtNameBook.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNameBook.Lines = new string[0];
            this.txtNameBook.Location = new System.Drawing.Point(261, 92);
            this.txtNameBook.Margin = new System.Windows.Forms.Padding(4);
            this.txtNameBook.MaxLength = 32767;
            this.txtNameBook.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNameBook.Modified = false;
            this.txtNameBook.Multiline = false;
            this.txtNameBook.Name = "txtNameBook";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNameBook.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.Silver;
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNameBook.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNameBook.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNameBook.OnIdleState = stateProperties20;
            this.txtNameBook.Padding = new System.Windows.Forms.Padding(4);
            this.txtNameBook.PasswordChar = '\0';
            this.txtNameBook.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNameBook.PlaceholderText = "Enter text";
            this.txtNameBook.ReadOnly = false;
            this.txtNameBook.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNameBook.SelectedText = "";
            this.txtNameBook.SelectionLength = 0;
            this.txtNameBook.SelectionStart = 0;
            this.txtNameBook.ShortcutsEnabled = true;
            this.txtNameBook.Size = new System.Drawing.Size(340, 48);
            this.txtNameBook.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNameBook.TabIndex = 95;
            this.txtNameBook.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNameBook.TextMarginBottom = 0;
            this.txtNameBook.TextMarginLeft = 3;
            this.txtNameBook.TextMarginTop = 1;
            this.txtNameBook.TextPlaceholder = "Enter text";
            this.txtNameBook.UseSystemPasswordChar = false;
            this.txtNameBook.WordWrap = true;
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.BackColor = System.Drawing.Color.White;
            this.label8.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.label8.Location = new System.Drawing.Point(648, 290);
            this.label8.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(132, 19);
            this.label8.TabIndex = 106;
            this.label8.Text = "Number of books";
            // 
            // txtSoLuong
            // 
            this.txtSoLuong.AcceptsReturn = false;
            this.txtSoLuong.AcceptsTab = false;
            this.txtSoLuong.AnimationSpeed = 200;
            this.txtSoLuong.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSoLuong.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSoLuong.AutoSizeHeight = true;
            this.txtSoLuong.BackColor = System.Drawing.Color.Transparent;
            this.txtSoLuong.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSoLuong.BackgroundImage")));
            this.txtSoLuong.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.txtSoLuong.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtSoLuong.BorderColorDisabled = System.Drawing.Color.Silver;
            this.txtSoLuong.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSoLuong.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.txtSoLuong.BorderRadius = 15;
            this.txtSoLuong.BorderThickness = 1;
            this.txtSoLuong.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSoLuong.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSoLuong.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtSoLuong.DefaultText = "";
            this.txtSoLuong.FillColor = System.Drawing.Color.White;
            this.txtSoLuong.HideSelection = true;
            this.txtSoLuong.IconLeft = null;
            this.txtSoLuong.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSoLuong.IconPadding = 10;
            this.txtSoLuong.IconRight = null;
            this.txtSoLuong.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSoLuong.Lines = new string[0];
            this.txtSoLuong.Location = new System.Drawing.Point(819, 272);
            this.txtSoLuong.Margin = new System.Windows.Forms.Padding(4);
            this.txtSoLuong.MaxLength = 32767;
            this.txtSoLuong.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSoLuong.Modified = false;
            this.txtSoLuong.Multiline = false;
            this.txtSoLuong.Name = "txtSoLuong";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSoLuong.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.Silver;
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSoLuong.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSoLuong.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSoLuong.OnIdleState = stateProperties24;
            this.txtSoLuong.Padding = new System.Windows.Forms.Padding(4);
            this.txtSoLuong.PasswordChar = '\0';
            this.txtSoLuong.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSoLuong.PlaceholderText = "Enter text";
            this.txtSoLuong.ReadOnly = false;
            this.txtSoLuong.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSoLuong.SelectedText = "";
            this.txtSoLuong.SelectionLength = 0;
            this.txtSoLuong.SelectionStart = 0;
            this.txtSoLuong.ShortcutsEnabled = true;
            this.txtSoLuong.Size = new System.Drawing.Size(340, 48);
            this.txtSoLuong.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSoLuong.TabIndex = 107;
            this.txtSoLuong.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSoLuong.TextMarginBottom = 0;
            this.txtSoLuong.TextMarginLeft = 3;
            this.txtSoLuong.TextMarginTop = 1;
            this.txtSoLuong.TextPlaceholder = "Enter text";
            this.txtSoLuong.UseSystemPasswordChar = false;
            this.txtSoLuong.WordWrap = true;
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 25;
            this.bunifuElipse1.TargetControl = this;
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.BackColor = System.Drawing.Color.White;
            this.label9.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label9.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.label9.Location = new System.Drawing.Point(126, 229);
            this.label9.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(72, 19);
            this.label9.TabIndex = 108;
            this.label9.Text = "Category";
            // 
            // txtNamxuatban
            // 
            this.txtNamxuatban.AcceptsReturn = false;
            this.txtNamxuatban.AcceptsTab = false;
            this.txtNamxuatban.AnimationSpeed = 200;
            this.txtNamxuatban.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNamxuatban.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNamxuatban.AutoSizeHeight = true;
            this.txtNamxuatban.BackColor = System.Drawing.Color.Transparent;
            this.txtNamxuatban.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNamxuatban.BackgroundImage")));
            this.txtNamxuatban.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.txtNamxuatban.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNamxuatban.BorderColorDisabled = System.Drawing.Color.Silver;
            this.txtNamxuatban.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNamxuatban.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.txtNamxuatban.BorderRadius = 15;
            this.txtNamxuatban.BorderThickness = 1;
            this.txtNamxuatban.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNamxuatban.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNamxuatban.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtNamxuatban.DefaultText = "";
            this.txtNamxuatban.FillColor = System.Drawing.Color.White;
            this.txtNamxuatban.HideSelection = true;
            this.txtNamxuatban.IconLeft = null;
            this.txtNamxuatban.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNamxuatban.IconPadding = 10;
            this.txtNamxuatban.IconRight = null;
            this.txtNamxuatban.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNamxuatban.Lines = new string[0];
            this.txtNamxuatban.Location = new System.Drawing.Point(262, 274);
            this.txtNamxuatban.Margin = new System.Windows.Forms.Padding(4);
            this.txtNamxuatban.MaxLength = 32767;
            this.txtNamxuatban.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNamxuatban.Modified = false;
            this.txtNamxuatban.Multiline = false;
            this.txtNamxuatban.Name = "txtNamxuatban";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNamxuatban.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.Silver;
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNamxuatban.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNamxuatban.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNamxuatban.OnIdleState = stateProperties32;
            this.txtNamxuatban.Padding = new System.Windows.Forms.Padding(4);
            this.txtNamxuatban.PasswordChar = '\0';
            this.txtNamxuatban.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNamxuatban.PlaceholderText = "Enter text";
            this.txtNamxuatban.ReadOnly = false;
            this.txtNamxuatban.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNamxuatban.SelectedText = "";
            this.txtNamxuatban.SelectionLength = 0;
            this.txtNamxuatban.SelectionStart = 0;
            this.txtNamxuatban.ShortcutsEnabled = true;
            this.txtNamxuatban.Size = new System.Drawing.Size(340, 48);
            this.txtNamxuatban.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNamxuatban.TabIndex = 110;
            this.txtNamxuatban.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNamxuatban.TextMarginBottom = 0;
            this.txtNamxuatban.TextMarginLeft = 3;
            this.txtNamxuatban.TextMarginTop = 1;
            this.txtNamxuatban.TextPlaceholder = "Enter text";
            this.txtNamxuatban.UseSystemPasswordChar = false;
            this.txtNamxuatban.WordWrap = true;
            // 
            // txtTheLoai
            // 
            this.txtTheLoai.AcceptsReturn = false;
            this.txtTheLoai.AcceptsTab = false;
            this.txtTheLoai.AnimationSpeed = 200;
            this.txtTheLoai.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTheLoai.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTheLoai.AutoSizeHeight = true;
            this.txtTheLoai.BackColor = System.Drawing.Color.Transparent;
            this.txtTheLoai.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTheLoai.BackgroundImage")));
            this.txtTheLoai.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.txtTheLoai.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtTheLoai.BorderColorDisabled = System.Drawing.Color.Silver;
            this.txtTheLoai.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtTheLoai.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.txtTheLoai.BorderRadius = 15;
            this.txtTheLoai.BorderThickness = 1;
            this.txtTheLoai.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTheLoai.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTheLoai.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtTheLoai.DefaultText = "";
            this.txtTheLoai.FillColor = System.Drawing.Color.White;
            this.txtTheLoai.HideSelection = true;
            this.txtTheLoai.IconLeft = null;
            this.txtTheLoai.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTheLoai.IconPadding = 10;
            this.txtTheLoai.IconRight = null;
            this.txtTheLoai.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTheLoai.Lines = new string[0];
            this.txtTheLoai.Location = new System.Drawing.Point(262, 211);
            this.txtTheLoai.Margin = new System.Windows.Forms.Padding(4);
            this.txtTheLoai.MaxLength = 32767;
            this.txtTheLoai.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTheLoai.Modified = false;
            this.txtTheLoai.Multiline = false;
            this.txtTheLoai.Name = "txtTheLoai";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTheLoai.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.Silver;
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTheLoai.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTheLoai.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTheLoai.OnIdleState = stateProperties28;
            this.txtTheLoai.Padding = new System.Windows.Forms.Padding(4);
            this.txtTheLoai.PasswordChar = '\0';
            this.txtTheLoai.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTheLoai.PlaceholderText = "Enter text";
            this.txtTheLoai.ReadOnly = false;
            this.txtTheLoai.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTheLoai.SelectedText = "";
            this.txtTheLoai.SelectionLength = 0;
            this.txtTheLoai.SelectionStart = 0;
            this.txtTheLoai.ShortcutsEnabled = true;
            this.txtTheLoai.Size = new System.Drawing.Size(340, 48);
            this.txtTheLoai.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTheLoai.TabIndex = 111;
            this.txtTheLoai.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTheLoai.TextMarginBottom = 0;
            this.txtTheLoai.TextMarginLeft = 3;
            this.txtTheLoai.TextMarginTop = 1;
            this.txtTheLoai.TextPlaceholder = "Enter text";
            this.txtTheLoai.UseSystemPasswordChar = false;
            this.txtTheLoai.WordWrap = true;
            // 
            // AddBook_WareHouse
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1271, 554);
            this.Controls.Add(this.txtTheLoai);
            this.Controls.Add(this.txtNamxuatban);
            this.Controls.Add(this.label9);
            this.Controls.Add(this.txtSoLuong);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.txtSoLanTaiBan);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.txtTacGia);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.bt_Exit);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.bt_OK);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.txtGiaBan);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.txtGiaMua);
            this.Controls.Add(this.bunifuPanel11);
            this.Controls.Add(this.txtNameBook);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(4);
            this.Name = "AddBook_WareHouse";
            this.Text = "AddBook_WareHouse";
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuTextBox txtSoLanTaiBan;
        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuTextBox txtTacGia;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bt_Exit;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bt_OK;
        private System.Windows.Forms.Label label6;
        private Bunifu.UI.WinForms.BunifuTextBox txtGiaBan;
        private System.Windows.Forms.Label label7;
        private Bunifu.UI.WinForms.BunifuTextBox txtGiaMua;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel11;
        private Bunifu.UI.WinForms.BunifuTextBox txtNameBook;
        private System.Windows.Forms.Label label8;
        private Bunifu.UI.WinForms.BunifuTextBox txtSoLuong;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private System.Windows.Forms.Label label9;
        private Bunifu.UI.WinForms.BunifuTextBox txtNamxuatban;
        private Bunifu.UI.WinForms.BunifuTextBox txtTheLoai;
    }
}