namespace QuanLyThuVienSach.GUI.GUI_ADMIN
{
    partial class Book_Details
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties113 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties114 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties115 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties116 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties117 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties118 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties119 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties120 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties121 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties122 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties123 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties124 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties125 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties126 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties127 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties128 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties129 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties130 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties131 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties132 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties133 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties134 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties135 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties136 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties137 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties138 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties139 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties140 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties141 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties142 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties143 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties144 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Book_Details));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties109 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties110 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties111 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties112 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.tb_Cetegory = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_ = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.tb_NumberOfBook = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_Year = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_Reprints = new Bunifu.UI.WinForms.BunifuTextBox();
            this.panel1 = new System.Windows.Forms.Panel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tb_Author = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.bt_Exit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.tb_SellingPrice = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label7 = new System.Windows.Forms.Label();
            this.tb_ImportPrice = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuPanel11 = new Bunifu.UI.WinForms.BunifuPanel();
            this.tb_NameBook = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_IDBook = new Bunifu.UI.WinForms.BunifuTextBox();
            this.ID = new System.Windows.Forms.Label();
            this.panel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 25;
            this.bunifuElipse1.TargetControl = this;
            // 
            // tb_Cetegory
            // 
            this.tb_Cetegory.AcceptsReturn = false;
            this.tb_Cetegory.AcceptsTab = false;
            this.tb_Cetegory.AnimationSpeed = 200;
            this.tb_Cetegory.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_Cetegory.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_Cetegory.AutoSizeHeight = true;
            this.tb_Cetegory.BackColor = System.Drawing.Color.Transparent;
            this.tb_Cetegory.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_Cetegory.BackgroundImage")));
            this.tb_Cetegory.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.tb_Cetegory.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_Cetegory.BorderColorDisabled = System.Drawing.Color.Silver;
            this.tb_Cetegory.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_Cetegory.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.tb_Cetegory.BorderRadius = 15;
            this.tb_Cetegory.BorderThickness = 1;
            this.tb_Cetegory.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_Cetegory.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Cetegory.DefaultFont = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tb_Cetegory.DefaultText = "";
            this.tb_Cetegory.FillColor = System.Drawing.Color.White;
            this.tb_Cetegory.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.tb_Cetegory.HideSelection = true;
            this.tb_Cetegory.IconLeft = null;
            this.tb_Cetegory.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Cetegory.IconPadding = 10;
            this.tb_Cetegory.IconRight = null;
            this.tb_Cetegory.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Cetegory.Lines = new string[0];
            this.tb_Cetegory.Location = new System.Drawing.Point(205, 173);
            this.tb_Cetegory.MaxLength = 32767;
            this.tb_Cetegory.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_Cetegory.Modified = false;
            this.tb_Cetegory.Multiline = false;
            this.tb_Cetegory.Name = "tb_Cetegory";
            stateProperties113.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties113.FillColor = System.Drawing.Color.Empty;
            stateProperties113.ForeColor = System.Drawing.Color.Empty;
            stateProperties113.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Cetegory.OnActiveState = stateProperties113;
            stateProperties114.BorderColor = System.Drawing.Color.Silver;
            stateProperties114.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties114.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties114.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_Cetegory.OnDisabledState = stateProperties114;
            stateProperties115.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties115.FillColor = System.Drawing.Color.Empty;
            stateProperties115.ForeColor = System.Drawing.Color.Empty;
            stateProperties115.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Cetegory.OnHoverState = stateProperties115;
            stateProperties116.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            stateProperties116.FillColor = System.Drawing.Color.White;
            stateProperties116.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            stateProperties116.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Cetegory.OnIdleState = stateProperties116;
            this.tb_Cetegory.Padding = new System.Windows.Forms.Padding(3);
            this.tb_Cetegory.PasswordChar = '\0';
            this.tb_Cetegory.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_Cetegory.PlaceholderText = "Enter";
            this.tb_Cetegory.ReadOnly = true;
            this.tb_Cetegory.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_Cetegory.SelectedText = "";
            this.tb_Cetegory.SelectionLength = 0;
            this.tb_Cetegory.SelectionStart = 0;
            this.tb_Cetegory.ShortcutsEnabled = true;
            this.tb_Cetegory.Size = new System.Drawing.Size(255, 36);
            this.tb_Cetegory.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_Cetegory.TabIndex = 195;
            this.tb_Cetegory.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_Cetegory.TextMarginBottom = 0;
            this.tb_Cetegory.TextMarginLeft = 3;
            this.tb_Cetegory.TextMarginTop = 0;
            this.tb_Cetegory.TextPlaceholder = "Enter";
            this.tb_Cetegory.UseSystemPasswordChar = false;
            this.tb_Cetegory.WordWrap = true;
            // 
            // tb_
            // 
            this.tb_.AutoSize = true;
            this.tb_.BackColor = System.Drawing.Color.White;
            this.tb_.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tb_.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.tb_.Location = new System.Drawing.Point(95, 186);
            this.tb_.Name = "tb_";
            this.tb_.Size = new System.Drawing.Size(58, 16);
            this.tb_.TabIndex = 194;
            this.tb_.Text = "Cetegory";
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.BackColor = System.Drawing.Color.White;
            this.label8.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.label8.Location = new System.Drawing.Point(494, 236);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(100, 16);
            this.label8.TabIndex = 192;
            this.label8.Text = "Number of Book";
            // 
            // tb_NumberOfBook
            // 
            this.tb_NumberOfBook.AcceptsReturn = false;
            this.tb_NumberOfBook.AcceptsTab = false;
            this.tb_NumberOfBook.AnimationSpeed = 200;
            this.tb_NumberOfBook.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_NumberOfBook.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_NumberOfBook.AutoSizeHeight = true;
            this.tb_NumberOfBook.BackColor = System.Drawing.Color.Transparent;
            this.tb_NumberOfBook.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_NumberOfBook.BackgroundImage")));
            this.tb_NumberOfBook.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.tb_NumberOfBook.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_NumberOfBook.BorderColorDisabled = System.Drawing.Color.Silver;
            this.tb_NumberOfBook.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_NumberOfBook.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.tb_NumberOfBook.BorderRadius = 15;
            this.tb_NumberOfBook.BorderThickness = 1;
            this.tb_NumberOfBook.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_NumberOfBook.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_NumberOfBook.DefaultFont = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tb_NumberOfBook.DefaultText = "";
            this.tb_NumberOfBook.FillColor = System.Drawing.Color.White;
            this.tb_NumberOfBook.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.tb_NumberOfBook.HideSelection = true;
            this.tb_NumberOfBook.IconLeft = null;
            this.tb_NumberOfBook.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_NumberOfBook.IconPadding = 10;
            this.tb_NumberOfBook.IconRight = null;
            this.tb_NumberOfBook.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_NumberOfBook.Lines = new string[0];
            this.tb_NumberOfBook.Location = new System.Drawing.Point(623, 226);
            this.tb_NumberOfBook.MaxLength = 32767;
            this.tb_NumberOfBook.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_NumberOfBook.Modified = false;
            this.tb_NumberOfBook.Multiline = false;
            this.tb_NumberOfBook.Name = "tb_NumberOfBook";
            stateProperties117.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties117.FillColor = System.Drawing.Color.Empty;
            stateProperties117.ForeColor = System.Drawing.Color.Empty;
            stateProperties117.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_NumberOfBook.OnActiveState = stateProperties117;
            stateProperties118.BorderColor = System.Drawing.Color.Silver;
            stateProperties118.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties118.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties118.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_NumberOfBook.OnDisabledState = stateProperties118;
            stateProperties119.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties119.FillColor = System.Drawing.Color.Empty;
            stateProperties119.ForeColor = System.Drawing.Color.Empty;
            stateProperties119.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_NumberOfBook.OnHoverState = stateProperties119;
            stateProperties120.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            stateProperties120.FillColor = System.Drawing.Color.White;
            stateProperties120.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            stateProperties120.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_NumberOfBook.OnIdleState = stateProperties120;
            this.tb_NumberOfBook.Padding = new System.Windows.Forms.Padding(3);
            this.tb_NumberOfBook.PasswordChar = '\0';
            this.tb_NumberOfBook.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_NumberOfBook.PlaceholderText = "Enter";
            this.tb_NumberOfBook.ReadOnly = true;
            this.tb_NumberOfBook.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_NumberOfBook.SelectedText = "";
            this.tb_NumberOfBook.SelectionLength = 0;
            this.tb_NumberOfBook.SelectionStart = 0;
            this.tb_NumberOfBook.ShortcutsEnabled = true;
            this.tb_NumberOfBook.Size = new System.Drawing.Size(255, 36);
            this.tb_NumberOfBook.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_NumberOfBook.TabIndex = 193;
            this.tb_NumberOfBook.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_NumberOfBook.TextMarginBottom = 0;
            this.tb_NumberOfBook.TextMarginLeft = 3;
            this.tb_NumberOfBook.TextMarginTop = 0;
            this.tb_NumberOfBook.TextPlaceholder = "Enter";
            this.tb_NumberOfBook.UseSystemPasswordChar = false;
            this.tb_NumberOfBook.WordWrap = true;
            // 
            // tb_Year
            // 
            this.tb_Year.AcceptsReturn = false;
            this.tb_Year.AcceptsTab = false;
            this.tb_Year.AnimationSpeed = 200;
            this.tb_Year.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_Year.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_Year.AutoSizeHeight = true;
            this.tb_Year.BackColor = System.Drawing.Color.Transparent;
            this.tb_Year.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_Year.BackgroundImage")));
            this.tb_Year.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.tb_Year.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_Year.BorderColorDisabled = System.Drawing.Color.Silver;
            this.tb_Year.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_Year.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.tb_Year.BorderRadius = 15;
            this.tb_Year.BorderThickness = 1;
            this.tb_Year.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_Year.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Year.DefaultFont = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tb_Year.DefaultText = "";
            this.tb_Year.FillColor = System.Drawing.Color.White;
            this.tb_Year.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.tb_Year.HideSelection = true;
            this.tb_Year.IconLeft = null;
            this.tb_Year.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Year.IconPadding = 10;
            this.tb_Year.IconRight = null;
            this.tb_Year.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Year.Lines = new string[0];
            this.tb_Year.Location = new System.Drawing.Point(205, 275);
            this.tb_Year.MaxLength = 32767;
            this.tb_Year.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_Year.Modified = false;
            this.tb_Year.Multiline = false;
            this.tb_Year.Name = "tb_Year";
            stateProperties121.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties121.FillColor = System.Drawing.Color.Empty;
            stateProperties121.ForeColor = System.Drawing.Color.Empty;
            stateProperties121.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Year.OnActiveState = stateProperties121;
            stateProperties122.BorderColor = System.Drawing.Color.Silver;
            stateProperties122.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties122.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties122.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_Year.OnDisabledState = stateProperties122;
            stateProperties123.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties123.FillColor = System.Drawing.Color.Empty;
            stateProperties123.ForeColor = System.Drawing.Color.Empty;
            stateProperties123.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Year.OnHoverState = stateProperties123;
            stateProperties124.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            stateProperties124.FillColor = System.Drawing.Color.White;
            stateProperties124.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            stateProperties124.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Year.OnIdleState = stateProperties124;
            this.tb_Year.Padding = new System.Windows.Forms.Padding(3);
            this.tb_Year.PasswordChar = '\0';
            this.tb_Year.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_Year.PlaceholderText = "Enter";
            this.tb_Year.ReadOnly = true;
            this.tb_Year.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_Year.SelectedText = "";
            this.tb_Year.SelectionLength = 0;
            this.tb_Year.SelectionStart = 0;
            this.tb_Year.ShortcutsEnabled = true;
            this.tb_Year.Size = new System.Drawing.Size(255, 36);
            this.tb_Year.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_Year.TabIndex = 191;
            this.tb_Year.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_Year.TextMarginBottom = 0;
            this.tb_Year.TextMarginLeft = 3;
            this.tb_Year.TextMarginTop = 0;
            this.tb_Year.TextPlaceholder = "Enter";
            this.tb_Year.UseSystemPasswordChar = false;
            this.tb_Year.WordWrap = true;
            // 
            // tb_Reprints
            // 
            this.tb_Reprints.AcceptsReturn = false;
            this.tb_Reprints.AcceptsTab = false;
            this.tb_Reprints.AnimationSpeed = 200;
            this.tb_Reprints.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_Reprints.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_Reprints.AutoSizeHeight = true;
            this.tb_Reprints.BackColor = System.Drawing.Color.Transparent;
            this.tb_Reprints.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_Reprints.BackgroundImage")));
            this.tb_Reprints.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.tb_Reprints.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_Reprints.BorderColorDisabled = System.Drawing.Color.Silver;
            this.tb_Reprints.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_Reprints.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.tb_Reprints.BorderRadius = 15;
            this.tb_Reprints.BorderThickness = 1;
            this.tb_Reprints.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_Reprints.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Reprints.DefaultFont = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tb_Reprints.DefaultText = "";
            this.tb_Reprints.FillColor = System.Drawing.Color.White;
            this.tb_Reprints.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.tb_Reprints.HideSelection = true;
            this.tb_Reprints.IconLeft = null;
            this.tb_Reprints.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Reprints.IconPadding = 10;
            this.tb_Reprints.IconRight = null;
            this.tb_Reprints.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Reprints.Lines = new string[0];
            this.tb_Reprints.Location = new System.Drawing.Point(623, 75);
            this.tb_Reprints.MaxLength = 32767;
            this.tb_Reprints.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_Reprints.Modified = false;
            this.tb_Reprints.Multiline = false;
            this.tb_Reprints.Name = "tb_Reprints";
            stateProperties125.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties125.FillColor = System.Drawing.Color.Empty;
            stateProperties125.ForeColor = System.Drawing.Color.Empty;
            stateProperties125.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Reprints.OnActiveState = stateProperties125;
            stateProperties126.BorderColor = System.Drawing.Color.Silver;
            stateProperties126.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties126.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties126.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_Reprints.OnDisabledState = stateProperties126;
            stateProperties127.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties127.FillColor = System.Drawing.Color.Empty;
            stateProperties127.ForeColor = System.Drawing.Color.Empty;
            stateProperties127.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Reprints.OnHoverState = stateProperties127;
            stateProperties128.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            stateProperties128.FillColor = System.Drawing.Color.White;
            stateProperties128.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            stateProperties128.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Reprints.OnIdleState = stateProperties128;
            this.tb_Reprints.Padding = new System.Windows.Forms.Padding(3);
            this.tb_Reprints.PasswordChar = '\0';
            this.tb_Reprints.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_Reprints.PlaceholderText = "Enter";
            this.tb_Reprints.ReadOnly = true;
            this.tb_Reprints.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_Reprints.SelectedText = "";
            this.tb_Reprints.SelectionLength = 0;
            this.tb_Reprints.SelectionStart = 0;
            this.tb_Reprints.ShortcutsEnabled = true;
            this.tb_Reprints.Size = new System.Drawing.Size(255, 36);
            this.tb_Reprints.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_Reprints.TabIndex = 184;
            this.tb_Reprints.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_Reprints.TextMarginBottom = 0;
            this.tb_Reprints.TextMarginLeft = 3;
            this.tb_Reprints.TextMarginTop = 0;
            this.tb_Reprints.TextPlaceholder = "Enter";
            this.tb_Reprints.UseSystemPasswordChar = false;
            this.tb_Reprints.WordWrap = true;
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.panel1.Controls.Add(this.bunifuLabel1);
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(954, 48);
            this.panel1.TabIndex = 188;
            this.panel1.MouseDown += new System.Windows.Forms.MouseEventHandler(this.panel1_MouseDown);
            this.panel1.MouseMove += new System.Windows.Forms.MouseEventHandler(this.panel1_MouseMove);
            this.panel1.MouseUp += new System.Windows.Forms.MouseEventHandler(this.panel1_MouseUp);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.AutoSize = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Microsoft Tai Le", 11.25F);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.DarkGray;
            this.bunifuLabel1.Location = new System.Drawing.Point(15, 15);
            this.bunifuLabel1.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(66, 19);
            this.bunifuLabel1.TabIndex = 88;
            this.bunifuLabel1.Text = "Book";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tb_Author
            // 
            this.tb_Author.AcceptsReturn = false;
            this.tb_Author.AcceptsTab = false;
            this.tb_Author.AnimationSpeed = 200;
            this.tb_Author.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_Author.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_Author.AutoSizeHeight = true;
            this.tb_Author.BackColor = System.Drawing.Color.Transparent;
            this.tb_Author.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_Author.BackgroundImage")));
            this.tb_Author.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.tb_Author.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_Author.BorderColorDisabled = System.Drawing.Color.Silver;
            this.tb_Author.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_Author.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.tb_Author.BorderRadius = 15;
            this.tb_Author.BorderThickness = 1;
            this.tb_Author.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_Author.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Author.DefaultFont = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tb_Author.DefaultText = "";
            this.tb_Author.FillColor = System.Drawing.Color.White;
            this.tb_Author.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.tb_Author.HideSelection = true;
            this.tb_Author.IconLeft = null;
            this.tb_Author.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Author.IconPadding = 10;
            this.tb_Author.IconRight = null;
            this.tb_Author.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Author.Lines = new string[0];
            this.tb_Author.Location = new System.Drawing.Point(205, 223);
            this.tb_Author.MaxLength = 32767;
            this.tb_Author.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_Author.Modified = false;
            this.tb_Author.Multiline = false;
            this.tb_Author.Name = "tb_Author";
            stateProperties129.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties129.FillColor = System.Drawing.Color.Empty;
            stateProperties129.ForeColor = System.Drawing.Color.Empty;
            stateProperties129.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Author.OnActiveState = stateProperties129;
            stateProperties130.BorderColor = System.Drawing.Color.Silver;
            stateProperties130.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties130.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties130.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_Author.OnDisabledState = stateProperties130;
            stateProperties131.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties131.FillColor = System.Drawing.Color.Empty;
            stateProperties131.ForeColor = System.Drawing.Color.Empty;
            stateProperties131.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Author.OnHoverState = stateProperties131;
            stateProperties132.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            stateProperties132.FillColor = System.Drawing.Color.White;
            stateProperties132.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            stateProperties132.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Author.OnIdleState = stateProperties132;
            this.tb_Author.Padding = new System.Windows.Forms.Padding(3);
            this.tb_Author.PasswordChar = '\0';
            this.tb_Author.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_Author.PlaceholderText = "Enter";
            this.tb_Author.ReadOnly = true;
            this.tb_Author.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_Author.SelectedText = "";
            this.tb_Author.SelectionLength = 0;
            this.tb_Author.SelectionStart = 0;
            this.tb_Author.ShortcutsEnabled = true;
            this.tb_Author.Size = new System.Drawing.Size(255, 36);
            this.tb_Author.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_Author.TabIndex = 190;
            this.tb_Author.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_Author.TextMarginBottom = 0;
            this.tb_Author.TextMarginLeft = 3;
            this.tb_Author.TextMarginTop = 0;
            this.tb_Author.TextPlaceholder = "Enter";
            this.tb_Author.UseSystemPasswordChar = false;
            this.tb_Author.WordWrap = true;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.Color.White;
            this.label3.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.label3.Location = new System.Drawing.Point(95, 236);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(46, 16);
            this.label3.TabIndex = 189;
            this.label3.Text = "Author";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.BackColor = System.Drawing.Color.White;
            this.label2.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.label2.Location = new System.Drawing.Point(95, 135);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(72, 16);
            this.label2.TabIndex = 175;
            this.label2.Text = "Name Book";
            // 
            // bt_Exit
            // 
            this.bt_Exit.AllowAnimations = true;
            this.bt_Exit.AllowMouseEffects = true;
            this.bt_Exit.AllowToggling = false;
            this.bt_Exit.AnimationSpeed = 200;
            this.bt_Exit.AutoGenerateColors = false;
            this.bt_Exit.AutoRoundBorders = false;
            this.bt_Exit.AutoSizeLeftIcon = true;
            this.bt_Exit.AutoSizeRightIcon = true;
            this.bt_Exit.BackColor = System.Drawing.Color.Transparent;
            this.bt_Exit.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.bt_Exit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bt_Exit.BackgroundImage")));
            this.bt_Exit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_Exit.ButtonText = "Exit";
            this.bt_Exit.ButtonTextMarginLeft = 0;
            this.bt_Exit.ColorContrastOnClick = 45;
            this.bt_Exit.ColorContrastOnHover = 45;
            this.bt_Exit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bt_Exit.CustomizableEdges = borderEdges4;
            this.bt_Exit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bt_Exit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bt_Exit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bt_Exit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bt_Exit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bt_Exit.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bt_Exit.ForeColor = System.Drawing.Color.DarkGray;
            this.bt_Exit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bt_Exit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bt_Exit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bt_Exit.IconMarginLeft = 11;
            this.bt_Exit.IconPadding = 14;
            this.bt_Exit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bt_Exit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bt_Exit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bt_Exit.IconSize = 5;
            this.bt_Exit.IdleBorderColor = System.Drawing.Color.Black;
            this.bt_Exit.IdleBorderRadius = 20;
            this.bt_Exit.IdleBorderThickness = 2;
            this.bt_Exit.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.bt_Exit.IdleIconLeftImage = null;
            this.bt_Exit.IdleIconRightImage = null;
            this.bt_Exit.IndicateFocus = false;
            this.bt_Exit.Location = new System.Drawing.Point(342, 353);
            this.bt_Exit.Name = "bt_Exit";
            this.bt_Exit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bt_Exit.OnDisabledState.BorderRadius = 20;
            this.bt_Exit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_Exit.OnDisabledState.BorderThickness = 2;
            this.bt_Exit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bt_Exit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bt_Exit.OnDisabledState.IconLeftImage = null;
            this.bt_Exit.OnDisabledState.IconRightImage = null;
            this.bt_Exit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bt_Exit.onHoverState.BorderRadius = 20;
            this.bt_Exit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_Exit.onHoverState.BorderThickness = 2;
            this.bt_Exit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bt_Exit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bt_Exit.onHoverState.IconLeftImage = null;
            this.bt_Exit.onHoverState.IconRightImage = null;
            this.bt_Exit.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.bt_Exit.OnIdleState.BorderRadius = 20;
            this.bt_Exit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_Exit.OnIdleState.BorderThickness = 2;
            this.bt_Exit.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.bt_Exit.OnIdleState.ForeColor = System.Drawing.Color.DarkGray;
            this.bt_Exit.OnIdleState.IconLeftImage = null;
            this.bt_Exit.OnIdleState.IconRightImage = null;
            this.bt_Exit.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.bt_Exit.OnPressedState.BorderRadius = 20;
            this.bt_Exit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_Exit.OnPressedState.BorderThickness = 2;
            this.bt_Exit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.bt_Exit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bt_Exit.OnPressedState.IconLeftImage = null;
            this.bt_Exit.OnPressedState.IconRightImage = null;
            this.bt_Exit.Size = new System.Drawing.Size(305, 40);
            this.bt_Exit.TabIndex = 187;
            this.bt_Exit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bt_Exit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bt_Exit.TextMarginLeft = 0;
            this.bt_Exit.TextPadding = new System.Windows.Forms.Padding(0);
            this.bt_Exit.UseDefaultRadiusAndThickness = true;
            this.bt_Exit.Click += new System.EventHandler(this.bt_Exit_Click);
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.BackColor = System.Drawing.Color.White;
            this.label4.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.label4.Location = new System.Drawing.Point(95, 285);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(90, 16);
            this.label4.TabIndex = 176;
            this.label4.Text = "Publishing year";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.BackColor = System.Drawing.Color.White;
            this.label5.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.label5.Location = new System.Drawing.Point(495, 137);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(77, 16);
            this.label5.TabIndex = 177;
            this.label5.Text = "Import price";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.BackColor = System.Drawing.Color.White;
            this.label6.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.label6.Location = new System.Drawing.Point(495, 188);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(75, 16);
            this.label6.TabIndex = 178;
            this.label6.Text = "Selling price";
            // 
            // tb_SellingPrice
            // 
            this.tb_SellingPrice.AcceptsReturn = false;
            this.tb_SellingPrice.AcceptsTab = false;
            this.tb_SellingPrice.AnimationSpeed = 200;
            this.tb_SellingPrice.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_SellingPrice.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_SellingPrice.AutoSizeHeight = true;
            this.tb_SellingPrice.BackColor = System.Drawing.Color.Transparent;
            this.tb_SellingPrice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_SellingPrice.BackgroundImage")));
            this.tb_SellingPrice.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.tb_SellingPrice.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_SellingPrice.BorderColorDisabled = System.Drawing.Color.Silver;
            this.tb_SellingPrice.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_SellingPrice.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.tb_SellingPrice.BorderRadius = 15;
            this.tb_SellingPrice.BorderThickness = 1;
            this.tb_SellingPrice.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_SellingPrice.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_SellingPrice.DefaultFont = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tb_SellingPrice.DefaultText = "";
            this.tb_SellingPrice.FillColor = System.Drawing.Color.White;
            this.tb_SellingPrice.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.tb_SellingPrice.HideSelection = true;
            this.tb_SellingPrice.IconLeft = null;
            this.tb_SellingPrice.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_SellingPrice.IconPadding = 10;
            this.tb_SellingPrice.IconRight = null;
            this.tb_SellingPrice.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_SellingPrice.Lines = new string[0];
            this.tb_SellingPrice.Location = new System.Drawing.Point(623, 174);
            this.tb_SellingPrice.MaxLength = 32767;
            this.tb_SellingPrice.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_SellingPrice.Modified = false;
            this.tb_SellingPrice.Multiline = false;
            this.tb_SellingPrice.Name = "tb_SellingPrice";
            stateProperties133.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties133.FillColor = System.Drawing.Color.Empty;
            stateProperties133.ForeColor = System.Drawing.Color.Empty;
            stateProperties133.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_SellingPrice.OnActiveState = stateProperties133;
            stateProperties134.BorderColor = System.Drawing.Color.Silver;
            stateProperties134.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties134.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties134.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_SellingPrice.OnDisabledState = stateProperties134;
            stateProperties135.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties135.FillColor = System.Drawing.Color.Empty;
            stateProperties135.ForeColor = System.Drawing.Color.Empty;
            stateProperties135.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_SellingPrice.OnHoverState = stateProperties135;
            stateProperties136.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            stateProperties136.FillColor = System.Drawing.Color.White;
            stateProperties136.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            stateProperties136.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_SellingPrice.OnIdleState = stateProperties136;
            this.tb_SellingPrice.Padding = new System.Windows.Forms.Padding(3);
            this.tb_SellingPrice.PasswordChar = '\0';
            this.tb_SellingPrice.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_SellingPrice.PlaceholderText = "Enter";
            this.tb_SellingPrice.ReadOnly = true;
            this.tb_SellingPrice.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_SellingPrice.SelectedText = "";
            this.tb_SellingPrice.SelectionLength = 0;
            this.tb_SellingPrice.SelectionStart = 0;
            this.tb_SellingPrice.ShortcutsEnabled = true;
            this.tb_SellingPrice.Size = new System.Drawing.Size(255, 36);
            this.tb_SellingPrice.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_SellingPrice.TabIndex = 183;
            this.tb_SellingPrice.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_SellingPrice.TextMarginBottom = 0;
            this.tb_SellingPrice.TextMarginLeft = 3;
            this.tb_SellingPrice.TextMarginTop = 0;
            this.tb_SellingPrice.TextPlaceholder = "Enter";
            this.tb_SellingPrice.UseSystemPasswordChar = false;
            this.tb_SellingPrice.WordWrap = true;
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.BackColor = System.Drawing.Color.White;
            this.label7.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.label7.Location = new System.Drawing.Point(494, 86);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(115, 16);
            this.label7.TabIndex = 179;
            this.label7.Text = "Number of reprints";
            // 
            // tb_ImportPrice
            // 
            this.tb_ImportPrice.AcceptsReturn = false;
            this.tb_ImportPrice.AcceptsTab = false;
            this.tb_ImportPrice.AnimationSpeed = 200;
            this.tb_ImportPrice.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_ImportPrice.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_ImportPrice.AutoSizeHeight = true;
            this.tb_ImportPrice.BackColor = System.Drawing.Color.Transparent;
            this.tb_ImportPrice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_ImportPrice.BackgroundImage")));
            this.tb_ImportPrice.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.tb_ImportPrice.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_ImportPrice.BorderColorDisabled = System.Drawing.Color.Silver;
            this.tb_ImportPrice.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_ImportPrice.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.tb_ImportPrice.BorderRadius = 15;
            this.tb_ImportPrice.BorderThickness = 1;
            this.tb_ImportPrice.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_ImportPrice.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_ImportPrice.DefaultFont = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tb_ImportPrice.DefaultText = "";
            this.tb_ImportPrice.FillColor = System.Drawing.Color.White;
            this.tb_ImportPrice.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.tb_ImportPrice.HideSelection = true;
            this.tb_ImportPrice.IconLeft = null;
            this.tb_ImportPrice.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_ImportPrice.IconPadding = 10;
            this.tb_ImportPrice.IconRight = null;
            this.tb_ImportPrice.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_ImportPrice.Lines = new string[0];
            this.tb_ImportPrice.Location = new System.Drawing.Point(623, 124);
            this.tb_ImportPrice.MaxLength = 32767;
            this.tb_ImportPrice.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_ImportPrice.Modified = false;
            this.tb_ImportPrice.Multiline = false;
            this.tb_ImportPrice.Name = "tb_ImportPrice";
            stateProperties137.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties137.FillColor = System.Drawing.Color.Empty;
            stateProperties137.ForeColor = System.Drawing.Color.Empty;
            stateProperties137.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_ImportPrice.OnActiveState = stateProperties137;
            stateProperties138.BorderColor = System.Drawing.Color.Silver;
            stateProperties138.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties138.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties138.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_ImportPrice.OnDisabledState = stateProperties138;
            stateProperties139.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties139.FillColor = System.Drawing.Color.Empty;
            stateProperties139.ForeColor = System.Drawing.Color.Empty;
            stateProperties139.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_ImportPrice.OnHoverState = stateProperties139;
            stateProperties140.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            stateProperties140.FillColor = System.Drawing.Color.White;
            stateProperties140.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            stateProperties140.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_ImportPrice.OnIdleState = stateProperties140;
            this.tb_ImportPrice.Padding = new System.Windows.Forms.Padding(3);
            this.tb_ImportPrice.PasswordChar = '\0';
            this.tb_ImportPrice.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_ImportPrice.PlaceholderText = "Enter";
            this.tb_ImportPrice.ReadOnly = true;
            this.tb_ImportPrice.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_ImportPrice.SelectedText = "";
            this.tb_ImportPrice.SelectionLength = 0;
            this.tb_ImportPrice.SelectionStart = 0;
            this.tb_ImportPrice.ShortcutsEnabled = true;
            this.tb_ImportPrice.Size = new System.Drawing.Size(255, 36);
            this.tb_ImportPrice.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_ImportPrice.TabIndex = 182;
            this.tb_ImportPrice.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_ImportPrice.TextMarginBottom = 0;
            this.tb_ImportPrice.TextMarginLeft = 3;
            this.tb_ImportPrice.TextMarginTop = 0;
            this.tb_ImportPrice.TextPlaceholder = "Enter";
            this.tb_ImportPrice.UseSystemPasswordChar = false;
            this.tb_ImportPrice.WordWrap = true;
            // 
            // bunifuPanel11
            // 
            this.bunifuPanel11.BackgroundColor = System.Drawing.Color.Gray;
            this.bunifuPanel11.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel11.BackgroundImage")));
            this.bunifuPanel11.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel11.BorderColor = System.Drawing.Color.Gray;
            this.bunifuPanel11.BorderRadius = 5;
            this.bunifuPanel11.BorderThickness = 0;
            this.bunifuPanel11.Enabled = false;
            this.bunifuPanel11.Location = new System.Drawing.Point(57, 75);
            this.bunifuPanel11.Name = "bunifuPanel11";
            this.bunifuPanel11.ShowBorders = true;
            this.bunifuPanel11.Size = new System.Drawing.Size(2, 250);
            this.bunifuPanel11.TabIndex = 180;
            // 
            // tb_NameBook
            // 
            this.tb_NameBook.AcceptsReturn = false;
            this.tb_NameBook.AcceptsTab = false;
            this.tb_NameBook.AnimationSpeed = 200;
            this.tb_NameBook.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_NameBook.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_NameBook.AutoSizeHeight = true;
            this.tb_NameBook.BackColor = System.Drawing.Color.Transparent;
            this.tb_NameBook.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_NameBook.BackgroundImage")));
            this.tb_NameBook.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.tb_NameBook.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_NameBook.BorderColorDisabled = System.Drawing.Color.Silver;
            this.tb_NameBook.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_NameBook.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.tb_NameBook.BorderRadius = 15;
            this.tb_NameBook.BorderThickness = 1;
            this.tb_NameBook.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_NameBook.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_NameBook.DefaultFont = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tb_NameBook.DefaultText = "";
            this.tb_NameBook.FillColor = System.Drawing.Color.White;
            this.tb_NameBook.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.tb_NameBook.HideSelection = true;
            this.tb_NameBook.IconLeft = null;
            this.tb_NameBook.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_NameBook.IconPadding = 10;
            this.tb_NameBook.IconRight = null;
            this.tb_NameBook.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_NameBook.Lines = new string[0];
            this.tb_NameBook.Location = new System.Drawing.Point(205, 124);
            this.tb_NameBook.MaxLength = 32767;
            this.tb_NameBook.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_NameBook.Modified = false;
            this.tb_NameBook.Multiline = false;
            this.tb_NameBook.Name = "tb_NameBook";
            stateProperties141.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties141.FillColor = System.Drawing.Color.Empty;
            stateProperties141.ForeColor = System.Drawing.Color.Empty;
            stateProperties141.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_NameBook.OnActiveState = stateProperties141;
            stateProperties142.BorderColor = System.Drawing.Color.Silver;
            stateProperties142.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties142.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties142.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_NameBook.OnDisabledState = stateProperties142;
            stateProperties143.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties143.FillColor = System.Drawing.Color.Empty;
            stateProperties143.ForeColor = System.Drawing.Color.Empty;
            stateProperties143.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_NameBook.OnHoverState = stateProperties143;
            stateProperties144.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            stateProperties144.FillColor = System.Drawing.Color.White;
            stateProperties144.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            stateProperties144.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_NameBook.OnIdleState = stateProperties144;
            this.tb_NameBook.Padding = new System.Windows.Forms.Padding(3);
            this.tb_NameBook.PasswordChar = '\0';
            this.tb_NameBook.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_NameBook.PlaceholderText = "Enter";
            this.tb_NameBook.ReadOnly = true;
            this.tb_NameBook.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_NameBook.SelectedText = "";
            this.tb_NameBook.SelectionLength = 0;
            this.tb_NameBook.SelectionStart = 0;
            this.tb_NameBook.ShortcutsEnabled = true;
            this.tb_NameBook.Size = new System.Drawing.Size(255, 36);
            this.tb_NameBook.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_NameBook.TabIndex = 181;
            this.tb_NameBook.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_NameBook.TextMarginBottom = 0;
            this.tb_NameBook.TextMarginLeft = 3;
            this.tb_NameBook.TextMarginTop = 0;
            this.tb_NameBook.TextPlaceholder = "Enter";
            this.tb_NameBook.UseSystemPasswordChar = false;
            this.tb_NameBook.WordWrap = true;
            // 
            // tb_IDBook
            // 
            this.tb_IDBook.AcceptsReturn = false;
            this.tb_IDBook.AcceptsTab = false;
            this.tb_IDBook.AnimationSpeed = 200;
            this.tb_IDBook.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_IDBook.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_IDBook.AutoSizeHeight = true;
            this.tb_IDBook.BackColor = System.Drawing.Color.Transparent;
            this.tb_IDBook.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_IDBook.BackgroundImage")));
            this.tb_IDBook.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.tb_IDBook.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_IDBook.BorderColorDisabled = System.Drawing.Color.Silver;
            this.tb_IDBook.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_IDBook.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.tb_IDBook.BorderRadius = 15;
            this.tb_IDBook.BorderThickness = 1;
            this.tb_IDBook.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_IDBook.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_IDBook.DefaultFont = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tb_IDBook.DefaultText = "";
            this.tb_IDBook.FillColor = System.Drawing.Color.White;
            this.tb_IDBook.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.tb_IDBook.HideSelection = true;
            this.tb_IDBook.IconLeft = null;
            this.tb_IDBook.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_IDBook.IconPadding = 10;
            this.tb_IDBook.IconRight = null;
            this.tb_IDBook.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_IDBook.Lines = new string[0];
            this.tb_IDBook.Location = new System.Drawing.Point(205, 75);
            this.tb_IDBook.MaxLength = 32767;
            this.tb_IDBook.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_IDBook.Modified = false;
            this.tb_IDBook.Multiline = false;
            this.tb_IDBook.Name = "tb_IDBook";
            stateProperties109.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties109.FillColor = System.Drawing.Color.Empty;
            stateProperties109.ForeColor = System.Drawing.Color.Empty;
            stateProperties109.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_IDBook.OnActiveState = stateProperties109;
            stateProperties110.BorderColor = System.Drawing.Color.Silver;
            stateProperties110.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties110.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties110.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_IDBook.OnDisabledState = stateProperties110;
            stateProperties111.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties111.FillColor = System.Drawing.Color.Empty;
            stateProperties111.ForeColor = System.Drawing.Color.Empty;
            stateProperties111.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_IDBook.OnHoverState = stateProperties111;
            stateProperties112.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            stateProperties112.FillColor = System.Drawing.Color.White;
            stateProperties112.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            stateProperties112.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_IDBook.OnIdleState = stateProperties112;
            this.tb_IDBook.Padding = new System.Windows.Forms.Padding(3);
            this.tb_IDBook.PasswordChar = '\0';
            this.tb_IDBook.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_IDBook.PlaceholderText = "Enter";
            this.tb_IDBook.ReadOnly = true;
            this.tb_IDBook.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_IDBook.SelectedText = "";
            this.tb_IDBook.SelectionLength = 0;
            this.tb_IDBook.SelectionStart = 0;
            this.tb_IDBook.ShortcutsEnabled = true;
            this.tb_IDBook.Size = new System.Drawing.Size(255, 36);
            this.tb_IDBook.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_IDBook.TabIndex = 197;
            this.tb_IDBook.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_IDBook.TextMarginBottom = 0;
            this.tb_IDBook.TextMarginLeft = 3;
            this.tb_IDBook.TextMarginTop = 0;
            this.tb_IDBook.TextPlaceholder = "Enter";
            this.tb_IDBook.UseSystemPasswordChar = false;
            this.tb_IDBook.WordWrap = true;
            // 
            // ID
            // 
            this.ID.AutoSize = true;
            this.ID.BackColor = System.Drawing.Color.White;
            this.ID.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ID.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.ID.Location = new System.Drawing.Point(95, 86);
            this.ID.Name = "ID";
            this.ID.Size = new System.Drawing.Size(52, 16);
            this.ID.TabIndex = 196;
            this.ID.Text = "ID Book";
            // 
            // Book_Details
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(954, 434);
            this.Controls.Add(this.tb_IDBook);
            this.Controls.Add(this.ID);
            this.Controls.Add(this.tb_Cetegory);
            this.Controls.Add(this.tb_);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.tb_NumberOfBook);
            this.Controls.Add(this.tb_Year);
            this.Controls.Add(this.tb_Reprints);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.tb_Author);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.bt_Exit);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.tb_SellingPrice);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.tb_ImportPrice);
            this.Controls.Add(this.bunifuPanel11);
            this.Controls.Add(this.tb_NameBook);
            this.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(4);
            this.Name = "Book_Details";
            this.Text = "Book_Details";
            this.panel1.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuTextBox tb_Cetegory;
        private System.Windows.Forms.Label tb_;
        private System.Windows.Forms.Label label8;
        private Bunifu.UI.WinForms.BunifuTextBox tb_NumberOfBook;
        private Bunifu.UI.WinForms.BunifuTextBox tb_Year;
        private Bunifu.UI.WinForms.BunifuTextBox tb_Reprints;
        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuTextBox tb_Author;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bt_Exit;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private Bunifu.UI.WinForms.BunifuTextBox tb_SellingPrice;
        private System.Windows.Forms.Label label7;
        private Bunifu.UI.WinForms.BunifuTextBox tb_ImportPrice;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel11;
        private Bunifu.UI.WinForms.BunifuTextBox tb_NameBook;
        private Bunifu.UI.WinForms.BunifuTextBox tb_IDBook;
        private System.Windows.Forms.Label ID;
    }
}