//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVienSach.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuNhapSach
    {
        public int ID_LichSuNhapSach { get; set; }
        public Nullable<int> MaSach { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<int> ID_Person { get; set; }
    
        public virtual Kho Kho { get; set; }
        public virtual Person Person { get; set; }
    }
}
